{% set name = "drf-spectacular" %}
{% set version = "0.27.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drf-spectacular-{{ version }}.tar.gz
  sha256: 18d7ae74b2b5d533fd31f1c591ebaa5cce1447e0976ced927401e3163040dea9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django >=2.2
    - djangorestframework >=3.10.3
    - uritemplate >=2.0.0
    - pyyaml >=5.1
    - jsonschema >=2.6.0
    - inflection >=0.3.1
    - typing-extensions

test:
  imports:
    - drf_spectacular
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tfranzel/drf-spectacular
  summary: Sane and flexible OpenAPI 3 schema generation for Django REST framework
  dev_url: https://github.com/tfranzel/drf-spectacular
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - MichelML
