{% set name = "drf-spectacular" %}
{% set version = "0.26.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drf-spectacular-{{ version }}.tar.gz
  sha256: 8f5a8f87353d1bb8dcb3f3909b7109b2dcbe1d91f3e069409cf322963e140bd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django >=2.2
    - djangorestframework >=3.10.3
    - uritemplate >=2.0.0
    - pyyaml >=5.1
    - jsonschema >=2.6.0
    - inflection >=0.3.1
    - typing-extensions

test:
  imports:
    - drf_spectacular
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tfranzel/drf-spectacular
  summary: Sane and flexible OpenAPI 3 schema generation for Django REST framework
  dev_url: https://github.com/tfranzel/drf-spectacular
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - MichelML
