{% set name = "drf-spectacular" %}
{% set version = "0.26.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drf-spectacular-{{ version }}.tar.gz
  sha256: b907a72a0244e5dcfeca625e9632cd8ebccdbe2cb528b7c1de1191708be6f31e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=2.2
    - djangorestframework >=3.10
    - inflection >=0.3.1
    - jsonschema >=2.6.0
    - python >=3.6
    - pyyaml >=5.1
    - uritemplate >=2.0.0

test:
  imports:
    - drf_spectacular
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tfranzel/drf-spectacular
  summary: Sane and flexible OpenAPI 3 schema generation for Django REST framework
  dev_url: https://github.com/tfranzel/drf-spectacular
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
